name: C++ CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]  # Testing across multiple platforms

    runs-on: ${{ matrix.os }}  # This ensures the job runs on the OS specified in the matrix

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up CMake
        uses: actions/setup-cmake@v1
        with:
          cmake-version: '3.19'

      - name: Set up GCC
        uses: actions/setup-gcc@v1
        with:
          gcc-version: '10'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtest-dev cmake build-essential

      - name: Build project
        run: |
          mkdir build
          cd build
          cmake ..
          make

      - name: Run tests
        run: |
          cd build
          ./tests  # Adjust this if the name of your test executable is different
