name: C++ CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]  # Testing across multiple platforms
    runs-on: ${{ matrix.os }}  # This ensures the job runs on the OS specified in the matrix

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up CMake
        uses: actions/setup-cmake@v2
        with:
          cmake-version: '3.21'  # Use a more recent version of CMake

      - name: Install dependencies
        run: |
          if [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
            sudo apt-get update
            sudo apt-get install -y libgtest-dev cmake build-essential g++
          elif [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System'
            choco install visualstudio2019buildtools
          elif [[ "${{ matrix.os }}" == "macos-latest" ]]; then
            brew install cmake
          fi

      - name: Build project
        run: |
          mkdir build
          cd build
          cmake ..  # CMake will automatically detect and configure the compiler based on the OS
          cmake --build .  # Build the project

      - name: Run tests
        run: |
          cd build
          ./tests  # Adjust if the name of your test executable is different
