name: C++ CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]  # Testing across multiple platforms
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up CMake
        uses: actions/setup-cmake@v2
        with:
          cmake-version: '3.21'

      - name: Install dependencies
        run: |
          if [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
            sudo apt-get update
            sudo apt-get install -y libgtest-dev cmake build-essential g++ 
          elif [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System'
            choco install visualstudio2019buildtools --package-parameters "--add Microsoft.VisualStudio.Component.VC.Tools.x86.x64"
            refreshenv
          elif [[ "${{ matrix.os }}" == "macos-latest" ]]; then
            brew install cmake
          fi

      - name: Build project
        run: |
          mkdir build
          cd build
          cmake ..  # Ensure correct CMakeLists.txt and test configurations
          cmake --build . --verbose  # Adds verbose output for troubleshooting

      - name: Run tests
        run: |
          cd build
          ./tests  # Replace with your actual test executable name
