name: C++ CI

on:
  push:
    branches:
      - main  # Trigger the workflow for changes to the main branch
  pull_request:
    branches:
      - main  # Trigger the workflow for PRs targeting the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # You can change this to macOS or Windows as needed

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]  # Testing across multiple platforms

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Checkout your code from GitHub

      - name: Set up CMake
        uses: actions/setup-cmake@v1
        with:
          cmake-version: '3.19'  # Use the correct CMake version for your project

      - name: Set up GCC
        uses: actions/setup-gcc@v1
        with:
          gcc-version: '10'  # Specify the correct GCC version for your project

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtest-dev cmake build-essential

      - name: Build project
        run: |
          mkdir build  # Create a build directory
          cd build  # Move into the build directory
          cmake ..  # Configure the project using CMake
          make  # Build the project

      - name: Run tests
        run: |
          cd build  # Move into the build directory where tests were compiled
          ./tests  # Run the tests (adjust if your test executable name is different)
